### ISSUE TITLE
Please provide details for applying the ML model & model parameter for PX4

### ISSUE THREAD

**Issue by wangwwno1** [DependableSystemsLab/pid-piper#1]
Current implementation returns a constant angular degree:
https://github.com/DependableSystemsLab/pid-piper/blob/0c37f412dac3e79cac7eae9f3dfbc33ac187959c/simulator/libraries/PID_Piper/LSTM.cpp#L1-L28
And the predicted outputs have no usage in the autopilot provided in the simulator.

So here is my questions:
1. How to use the predicted output for a Feed-Forward Control?
2. Is all of the experiments are based on the same LSTM model? If not, could you provide the model parameter in the PX4 experiment?
3. The input and output of the train dataset is inconsistent with the model API, and omitted the `gyro` `pos` `mag` `gpsVel` data, please re-check the train data and the model parameter in this repo.
https://github.com/DependableSystemsLab/pid-piper/blob/0c37f412dac3e79cac7eae9f3dfbc33ac187959c/simulator/libraries/PID_Piper/LSTM.cpp#L31-L40

**Comment by wangwwno1** [comment]
Thanks! I have made a double check about the code and there is a major issue.
With the current implementation, the function `recoveryMonitor` in class `PID_Piper` should return the corrected control output when the uav is under an overt attack. **However, I can't find any reference of `recoveryMonitor` in the autopilot code. It seems like the `PID_Piper` class can not modify the controller outputs as it return nothing to the autopilot.**

Do I missed something or there is a version inconsistency in the autopilot?

**Comment by dashpritam** [comment]
Thanks again for your interest. As said, we are working on this, and we will notify you once the autopilot files are fixed.

**Comment by dashpritam** [comment]
We have fixed this problem, the simulator code is updated. Please see the answers to your questions below: 
1. Take a look at libraries/AC_AttitudeControl/AC_AttitudeControl.cpp and libraries/PID_Piper/PID_Piper.cpp to understand the flow of the program. 
2. For Euler angles (yaw, roll, pitch) we use separate ML models. Single model cannot be used for predicting all three euler angles. See libraries/PID_Piper/models, PX4 models are available in this directory as well. 
3. The dataset contained RV mission data from a Pixhawk drone. The logs generated in the Pixhawk drone have a different headers, but it is comparable to the data used for ML predictions in the simuator. I will add a refined dataset soon to avoid the confusion you reported above. 

PID_Piper library can be plugged into PX4 autopilot easily. Add a new module in PX4 namely PID_Piper and adapt the code ArduCopter code from AC_AttitudeControl/AC_AttitudeControl.cpp and replicate it at PX4 code modules/mc_att_control/mc_att_control_main.cpp. 

Feel free to reach out if you have any more questions.

**Comment by wangwwno1** [comment]
Thank you @dashpritam！Much thanks for this fix! I'm working on it to replicate the experiment on PX4.

BTW I would like to report a (potential) inconsistency in the input of PID-piper: the pid-piper receive states from both `AC_AttitudeControl.cpp` and `AC_PosControl.cpp`, includes the horizonal velocity. This is controlled by variable `_vehicle_horiz_vel`, which is a 2D float array that host the horizonal velocity at both X-axis and Y-axis, as the update of `_vel_error` suggest:
https://github.com/DependableSystemsLab/pid-piper/blob/830ff1d0b50911aa2d0be859f8fd17b5a6355997/simulator/libraries/AC_AttitudeControl/AC_PosControl.cpp#L1064-L1075

While the PID-Piper model take both axis for `_vel_error`, it only accept the velocity of X-axis as input:
https://github.com/DependableSystemsLab/pid-piper/blob/830ff1d0b50911aa2d0be859f8fd17b5a6355997/simulator/libraries/AC_AttitudeControl/AC_PosControl.cpp#L1120-L1123

**Comment by wangwwno1** [comment]
Plus, could you tell me the equivalent variable of  `_ahrs.roll_sensor` in PX4?
https://github.com/DependableSystemsLab/pid-piper/blob/830ff1d0b50911aa2d0be859f8fd17b5a6355997/simulator/libraries/AC_AttitudeControl/AC_PosControl.cpp#L1125-L1131

**Comment by dashpritam** [comment]
This is not an inconsistency, some parameters are not needed for model predictions, sometimes they make the prediction worse. We have detailed this in the paper. 
`_ahrs.roll_sensor = degree(roll)*100`. I have detailed how to map in PX4 in issue#[3](https://github.com/DependableSystemsLab/pid-piper/issues/3)
