### ISSUE TITLE
On the model input in PX4-Autopilot

### ISSUE THREAD

**Issue by wangwwno1** [DependableSystemsLab/pid-piper#3]
Hi, I'm trying to integrate the PID-Piper to the PX4-Autopilot, but got problem in feeding the infos to the model.
I can use the `uORB` mechanism to subscribe `topic` and get the sensor data, but there are some inputs that I don't know which topic to subscribe. Most of them are related to the `_ahrs`:
https://github.com/DependableSystemsLab/pid-piper/blob/830ff1d0b50911aa2d0be859f8fd17b5a6355997/simulator/libraries/AC_AttitudeControl/AC_AttitudeControl.cpp#L273-L279

Here is my mapping for the inputs in ArduPilot and its corresponding `topic` in PX4:
ArduPilot    PX4-Autopilot
accXYZ    vehicle_local_position_setpoint  (not sure about it)
gyroXYZ    sensor_combined
posXYZ    vehicle_local_position
velX    vehicle_local_position
errorXY    *calculated from posXY and setpoint posXY from vehicle_local_position_setpoint *
velErrorXY    *calculated from velXY and setpoint velXY from vehicle_local_position_setpoint *

I'm not sure about the related topics of the ` _ahrs.**` variables.
Could you tell me the related topics in PX4-Autopilot?
Thanks in advance!

**Comment by dashpritam** [comment]
You can use `setpoint.{xxx}` in mc_pos_control to get acc, pos etc. example `setpoint.accleration[0]` for `accX`. 
AHRS is a program in Ardupilot that translates IMU measurements to X, Y, Z orientation. We use the sensor values before it is fed to the EKF, example: `_ahrs.get_gyro_latest().x` get the angular orientation in X axis. You can get the equivalent in PX4 in `modules/ekf2/EKF2.cpp` and use the corresponding params as inputs to the ML model. 

Feel free to reach out if you have any other questions.

**Comment by wangwwno1** [comment]
> You can use `setpoint.{xxx}` in mc_pos_control to get acc, pos etc. example `setpoint.accleration[0]` for `accX`.
> AHRS is a program in Ardupilot that translates IMU measurements to X, Y, Z orientation. We use the sensor values before it is fed to the EKF, example: `_ahrs.get_gyro_latest().x` get the angular orientation in X axis. You can get the equivalent in PX4 in `modules/ekf2/EKF2.cpp` and use the corresponding params as inputs to the ML model.
> 
> Feel free to reach out if you have any other questions.

Thanks! One more question: how do I get `_ahrs.get_error_rp()` and `_ahrs.get_error_yaw()` in PX4?

**Comment by wangwwno1** [comment]
@dashpritam @karthikp-ubc 
Hello, could you point out how to get `_ahrs.get_error_rp()` and `_ahrs.get_error_yaw()` in PX4 autopilot?
