### ISSUE TITLE
Request the CUSUM parameter setting for PX4 and ArduPilot experiment

### ISSUE THREAD

**Issue by wangwwno1** [DependableSystemsLab/pid-piper#4]
Hello again! The PID-Piper use CUSUM(delta = delta + residual - b) to calculate the error, but the original paper does not specify the value of `b`, could you provide the experimental details about these parameters?

**Comment by wangwwno1** [comment]
Plus, in the `recoveryMonitor`, the `checkSwitchControl` is written **AFTER** the return clause.
Which means, if the model detect an attack, it will **always** use the output of model `y_ML` till the end of mission.
This behavior seems inconsistent with the algorithm workflow (because it include a "deactivation" once the attack is subside). 
https://github.com/DependableSystemsLab/pid-piper/blob/e3f7a26d0f244611b12ab09d3b81abeda700fd14/simulator/libraries/PID_Piper/PID_Piper.hpp#L126-L145

**Comment by dashpritam** [comment]
Look at PID_Piper.h and PID_Piper.cpp files for the above details.

**Comment by wangwwno1** [comment]
> Look at PID_Piper.h and PID_Piper.cpp files for the above details.

This repo only provide PID-Piper for ArduPilot, should I use same values for the PX4?
