### ISSUE TITLE
[Bug]PID-Piper model expect position error as input, but got current position instead.

### ISSUE THREAD

**Issue by wangwwno1** [DependableSystemsLab/pid-piper#5]
https://github.com/DependableSystemsLab/pid-piper/blob/e3f7a26d0f244611b12ab09d3b81abeda700fd14/simulator/libraries/AC_AttitudeControl/AC_AttitudeControl.cpp#L273-L279

Line 277 should use `AC_AttitudeControl::errorX` and `AC_AttitudeControl::errorY` instead?

**Comment by dashpritam** [comment]
Yes it should be errorX and errorY.
